name: '"TODO" Diff Checker'
description: 'Check for "TODO" changes in PR by comparing base and head branches'
inputs:
  base-ref:
    description: 'Base branch reference for comparison'
    required: true
  head-ref:
    description: 'Head branch reference for comparison'
    required: true
outputs:
  has-changes:
    description: 'Whether there are "TODO" changes'
    value: ${{ steps.check-todos.outputs.has_changes }}
  summary:
    description: 'Summary of "TODO" changes'
    value: ${{ steps.check-todos.outputs.summary }}
  details:
    description: 'Detailed "TODO" changes in JSON format'
    value: ${{ steps.check-todos.outputs.details }}
runs:
  using: 'composite'
  steps:
    - name: Install ripgrep
      shell: bash
      run: |
        # Download ripgrep binary directly from GitHub releases (faster than apt-get)
        RG_VERSION="14.1.1"
        RG_ARCH="x86_64-unknown-linux-musl"
        curl -LO "https://github.com/BurntSushi/ripgrep/releases/download/${RG_VERSION}/ripgrep-${RG_VERSION}-${RG_ARCH}.tar.gz"
        tar xzf "ripgrep-${RG_VERSION}-${RG_ARCH}.tar.gz"
        sudo mv "ripgrep-${RG_VERSION}-${RG_ARCH}/rg" /usr/local/bin/
        rm -rf "ripgrep-${RG_VERSION}-${RG_ARCH}" "ripgrep-${RG_VERSION}-${RG_ARCH}.tar.gz"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Check "TODO" differences
      id: check-todos
      shell: bash
      run: |
        python ${{ github.action_path }}/check_todos.py \
          --base-ref "${{ inputs.base-ref }}" \
          --head-ref "${{ inputs.head-ref }}" \
          --github-output $GITHUB_OUTPUT
