site_name: bfabricPy docs
nav:
  - index.md
  - entities.md
  - good_to_know.md
  - contribute.md
  - changelog.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - mkdocstrings
