name: "Setup bfabricPy"
inputs:
  python-version:
    description: "Python version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install bfabricPy
      shell: bash
      run: |
        pip install uv
        uv pip install --system ".[dev]"
