application:
  input:
    FUSION_2:
    - bfabric@fgcz-proteomics.uzh.ch://srv/www/htdocs//p2122/Proteomics/FUSION_2/araldi_20170810/20170810_03_60275_ea55c-pbh_input.raw
    - bfabric@fgcz-proteomics.uzh.ch://srv/www/htdocs//p2122/Proteomics/FUSION_2/araldi_20170810/20170810_04_60274_ea55c-bhp_input.raw
  output:
  - bfabric@fgcz-proteomics.uzh.ch:/srv/www/htdocs//p2122/bfabric/Proteomics/ProteomeDiscovererQC/2017/2017-08/2017-08-11//workunit_157425//406037.html
  parameters:
    //WorkflowNode[@FriendlyName='PMI-Preview']//ProcessingNodeParameter[@Name='ArginineModificationMass']: None
    //WorkflowNode[@FriendlyName='PMI-Preview']//ProcessingNodeParameter[@Name='CysteineModificationMass']: +57.021464
      (carbamidomethylation)
    //WorkflowNode[@FriendlyName='PMI-Preview']//ProcessingNodeParameter[@Name='FastaDatabase']: uniprot-proteome_UP000002494.fasta
    //WorkflowNode[@FriendlyName='PMI-Preview']//ProcessingNodeParameter[@Name='LysineModificationMass']: None
    DiscovererDaemon: c:\Program Files\Thermo\Proteome Discoverer Daemon 2.1\System\Release\DiscovererDaemon.exe
    processingmode: batch
    workflow: QCpreview
    workflowbaseurl: http://fgcz-ms.uzh.ch/config/PD21/
  protocol: scp
job_configuration:
  executable: /home/bfabric/sgeworker/bin/fgcz_sge_proteome_discoverer21.bash
  external_job_id: 57336
  input:
    FUSION_2:
    - extract_id: 60275
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=60275
      resource_id: 405719
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=405719
      sample_id: 52174
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=52174
    - extract_id: 60274
      extract_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-extract.html?extractId=60274
      resource_id: 405718
      resource_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-resource.html?resourceId=405718
      sample_id: 52173
      sample_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-sample.html?sampleId=52173
  output:
    protocol: scp
    resource_id: 406037
    ssh_args: -o StrictHostKeyChecking=no -2 -l bfabric -x
  stderr:
    protocol: file
    resource_id: 406038
    url: /home/bfabric/sgeworker/logs/workunitid-157425_resourceid-406037.err
  stdout:
    protocol: file
    resource_id: 406039
    url: /home/bfabric/sgeworker/logs/workunitid-157425_resourceid-406037.out
  workunit_id: 157425
  workunit_url: http://fgcz-bfabric.uzh.ch/bfabric/userlab/show-workunit.html?workunitId=157425

