
    _cmd_script_header = """
    #!/bin/bash" 
    # generated by executing
    # $HeadURL: http://fgcz-svn.uzh.ch/repos/scripts/trunk/linux/bfabric/apps/python/wrapper_creator.py $
    # $Id: $
    #
    echo $0
    export PATH=$PATH:/bin/:/usr/bin/
    hostname
    pwd                            
    WORKUNIT=" + str(workunit._id) 
    ssh " + _outputStorage.host + " 'mkdir -p " + _outputStorage.basepath + _outputRelativePath + "' || exit 1\n"]
    """

    _cmd_script_header_list = ["#!/bin/bash\n", 
        "# generated by executing \n",
        "# $HeadURL: http://fgcz-svn.uzh.ch/repos/scripts/trunk/linux/bfabric/apps/python/wrapper_creator.py $\n",
        "# $Id: $\n\n",
        "echo $0\n",
        "export PATH=$PATH:/bin/:/usr/bin/\n\n",
