bfabric:
  app_runner: 'git+https://github.com/fgcz/bfabricPy@refactor-submitter#subdirectory=bfabric_app_runner'
versions:
  - version:
      - 0.1.0
    commands:
      dispatch:
        type: shell
        command: >
          uv run --locked --project /scratch/leo/code/bfabricPy/bfabric_app_runner/examples/file_table
          -m file_table_app.dispatch_bfabric
      process:
        type: shell
        command: bash /scratch/leo/code/bfabricPy/bfabric_app_runner/examples/file_table/process.bash
    submitter:
      name: slurm
