# TODO we need better means to handle the path to the app? or at least like a way to make the path relative to the
#      yaml available as a make template arg, maybe then we could already handle most of the issues
bfabric:
  app_runner: main
versions:
  - version:
      - 0.1.0
    commands:
      dispatch:
        type: shell
        command: |
          uv run --locked --project /Users/leo/code/bfabricPy/bfabric_app_runner/examples/file_table
          -m file_table.dispatch
      process:
        type: shell
        command: |
          uv run --locked --project /Users/leo/code/bfabricPy/bfabric_app_runner/examples/file_table
          snakemake
