@startuml
    title
      App Runner Activity Diagram
    end title

    start
    :workunit_ref]
    partition App Runner {
      :Retrieve workunit and app information;
      split
        :workunit_definition.yml]
      split again
      :app_definition.yml]
      note right
        These are maintained in a
        centralized repository.
      end note
      end split

      :Set workunit processing status;
      :""bfabric-app-runner action dispatch"";
      note right
        This step is supposed to be deterministic!
        To allow distributing the chunks in the future.
      end note
      split
        :chunks.yml]
      split again
        :chunk1/inputs.yml]
      split again
        :chunk2/inputs.yml]
      end split
    ' Unclear
    '  :Precondition check;
      :""bfabric-app-runner action run-all""]
    }

    note right
       chunks.yml lists all chunk directories;
       run-all processes each chunk in turn.
    end note
    fork
        :Stage inputs (chunk 1);
        partition App {
          :Process chunk 1;
          :outputs.yml]
        }
        :Register outputs;
    fork again
        :Stage inputs (chunk 2);
        partition App {
          :Process chunk 2;
          :outputs.yml]
        }
        :Register outputs;
    end fork

    :Set workunit available status;
    stop
@enduml
